### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by jinsmile1996** [wxjiao/HiGRUs#5]
Can you provide all the data sets used in this experiment?

**Comment by liuyijiang1994** [comment]
@jinsmile1996 这儿有：

**Comment by liuyijiang1994** [comment]
> Can you provide all the data sets used in this experiment?

@jinsmile1996 这儿有：http://doraemon.iis.sinica.edu.tw/emotionlines/download.html

**Comment by jinsmile1996** [comment]
> Can you provide all the data sets used in this experiment?
> 
> @jinsmile1996 这儿有：http://doraemon.iis.sinica.edu.tw/emotionlines/download.html

好的，谢谢

**Comment by wxjiao** [comment]
@jinsmile1996 You can refer to the links provided to acquire all the datasets as some may need authorization.
